name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Show Docker info
        run: |
          docker info
          docker version

      - name: "Step 1: 初始化环境"
        run: |
          python test_all.py --only-init 2>&1 | tee test_output_1_init.log
      - name: "Step 2: build"
        run: |
          docker exec telego-container go test ./test/test1_build/build_test.go -v 2>&1 | tee test_output_2_build.log
      - name: "Step 3: shortcut"
        run: |
          docker exec telego-container go test ./test/test2_build_and_run_shortcut/shortcut_test.go -v 2>&1 | tee test_output_3_shortcut.log
      - name: "Step 4: config"
        run: |
          docker exec telego-container go test ./test/test3_main_node_config/config_test.go -v 2>&1 | tee test_output_4_config.log

