name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Show Docker info
        run: |
          docker info
          docker version

      - name: "Step 1: 初始化环境"
        run: |
          python test_all.py --only-init
      - name: "Step 2: test test1-build build-test"
        run: |
          docker exec telego-container go test ./test/test1_build/build_test.go -v
      - name: "Step 3: test test2-build-and-run-shortcut shortcut-test"
        run: |
          docker exec telego-container go test ./test/test2_build_and_run_shortcut/shortcut_test.go -v
      - name: "Step 4: test test3-main-node-config config-test"
        run: |
          docker exec telego-container go test ./test/test3_main_node_config/config_test.go -v
      - name: "Step 5: test test4-img-repo img-repo-test"
        run: |
          docker exec telego-container go test ./test/test4_img_repo/img_repo_test.go -v

